config/routes.rb
Rails.application.routes.draw do
  root to: "main#index" 
  get "about", to: "about#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes

    attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {minimum: 1, maximum: 280}, presence: true
  validates :published_at, presence: true

  after_initialize do 
    self.published_at ||= 24.hour.from_now
  end

  after_save_commit do
    if published_at_previously_changed?
      TweetJob.set(wait_until: published_at).perform_later(self)
    end
  end

  def published?

    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)

  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  has_many :tweets
  belongs_to :user


  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
# email:string
# password:string
# password_confirmation:virtual string

class User < ApplicationRecord
    has_many :twitter_accounts
    has_many :tweets
    has_secure_password
    validates :email, presence: true, format: {
                                                 with: /\A[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\z/, 
                                                 message: "Must be a valid email address" 
                                                }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :set_current_user

    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end  
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed to do that!" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
       if session[:user_id]
        @user = User.find_by(id: session[:user_id])
       end
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController 
    def twitter
        twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
        twitter_account.update(
            name: auth.info.name,
            username: auth.info.nickname,
            image: auth.info.image,
            token: auth.credentials.token,
            secret: auth.credentials.secret
        )

        redirect_to twitter_accounts_path, notice: "Twitter account succesfully synced to your account!"
    end

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end
    def create
        @user = User.find_by(params[:user])

        if @user.present?
            # send email
            PasswordMailer.with(user: @user).reset.deliver_now

        end
        
        redirect_to root_path, notice: "We've sent an email concerning your password reset."

    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Token expired. Try again."
    end


    def update
        @user = User.find_signed(params[:token], purpose: "password_reset")

        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in!"
        else
            render :edit 
        end

    end

    private 
    def password_params
        
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit
    end
    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Updated Password Success"

        else
            render :edit
        end
    end 

    private
    def password_params

        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController


    def new
        @user = User.new
    end

    def create
       @user = User.new(user_params)
       if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Successfully created account!"
       else
        render :new
       end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
        
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Log in success!"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:edit, :update, :destroy]

    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweet = Tweet.new 
    end

    def create 
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
            redirect_to tweets_path, notice: "Tweet was scheduled successfully"
        else
            render :new 
        end
    end

    def edit
    end    
    
    def update
        if @tweet.update(tweet_params)
            redirect_to tweets_path, notice: "Tweet updated successfully!"
        else
            render :edit
        end
    end

    def destroy
        if @tweet.destroy
        redirect_to tweets_path, notice: "Tweet was deleted!"
        end
    end

    private 

    def tweet_params
        params.require(:tweet).permit(:twitter_account_id, :body, :published_at)
    end

    def set_tweet
        @tweet = Current.user.tweets.find(params[:id])
    end
end 

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_twitter_account, only: [:destroy]

    def index 
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy
        @twitter_account.destroy
        redirect_to twitter_accounts_path, notice: "Disconnected Twitter Account"
    end

    private

    def set_twitter_account
        @twitter_account = Current.user.twitter_accounts.find_by(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def render_title (title = '') 
        if title.empty?
            title = "Tweeter"
        else
            title = "#{title} | Tweeter"
        end
    end
end

app/views/about/index.html.erb
<% provide(:title, "About") %>
<h1>About Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= render_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render partial: 'shared/nav' %>
    <main class="container">
        <%= render partial: 'shared/flash' %>
        <%= yield %>
    </main>
</body>

</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome!</h1>

</div>

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>

<%if @user.errors.any? %>
<div class="alert alert-danger">
    <%@user.errors.full_messages.each do |message|%>
    <div>
        <%= message %>
    </div>
    <% end %>
</div>
<% end %>


<div class="form-group">
    <div class="mb-3">
        <%= f.label :password%>
        <%= f.password_field :password, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.label :password_confirmation  %>
        <%= f.password_field :password_confirmation, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.submit value: "Reset Password", class: "btn btn-primary"%>
    </div>
</div>
<%end%>

app/views/password_resets/new.html.erb
<h1>Forgot Your Password</h1>

<%= form_with url: password_reset_path do |f| %>
<div class="form-group">
    <div class="mb-3">
        <%= f.label :email  %>
        <%= f.text_field :email, class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= f.submit value: "Reset Password", class: "btn btn-primary"%>
    </div>
</div>
<%end%>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-success mt-4" role="alert">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert]%>
<div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_form_errors.html.erb
<%if f.object.errors.any? %>
<div class="alert alert-danger">
    <% f.object.errors.full_messages.each do |message|%>
    <div>
        <%= message %>
    </div>
    <% end %>
</div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Tweeter", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Tweets", tweets_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link"%>
            </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <% if Current.user %>
            <li class="nav-item">
                <%= link_to Current.user.email, edit_password_path, class: 'nav-link' %></span>
            </li>
            <li class="nav-item">
                <%= button_to "Logout", logout_path, method: :delete, class: "nav-link btn" %>
            </li>
            <%else %>
            <li class="nav-item">
                <%= link_to "Login", sign_in_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
            </li>
            <%end%>

        </ul>
    </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |f| %>
<%= render 'shared/form_errors', f: f %>

<div class="mb-3">
    <%= f.label :twitter_account_id %>
    <%= f.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, class: "form-control" %>
    <%= link_to "Sync up your Twitter", '/auth/twitter/', class: '' %>
</div>

<div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
</div>

<div class="mb-3">
    <%= f.label :published_at %>
    <div class="form-control">
        <%= f.datetime_select :published_at %>
    </div>
</div>

<%= f.button "Schedule", class: "btn btn-primary" %>

<% if f.object.persisted? %>
<%= link_to "Delete", f.object, method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-outline-danger' %>
<% end %>


<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3">
    <div class="p-4 mb-3">
        <strong><%= tweet.body%></strong>
    </div>
    <div class="d-flex align-items-center mb-4">
        <div class="me-4">
            <%= image_tag tweet.twitter_account.image, class: "rounded-circle"%>
            <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>
        </div>
    </div>
    <% if tweet.published? %>
    <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <% else %>
    Scheduled for <%= l tweet.published_at, format: :short %>
    <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
    <% end %>

    <hr class="w-50">
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet </h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">

    <h1>Tweets</h1>

    <% if Current.user.twitter_accounts.any? %>

    <%= link_to "Schedule Tweet", new_tweet_path, class: "btn btn-primary" %>

    <% else %>

    <%= link_to "Sync up your Twitter", '/auth/twitter/', class: 'btn btn-primary' %>

    <% end %>


</div>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet </h1>

<%= render "form", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
    <h1>Twitter Accounts</h1>

    <%= button_to 'Link to Twitter', '/auth/twitter', class: "btn, btn-primary" %>
</div>
<br><br>
<%  @twitter_accounts.each do |twitter_account|%>
<div class="d-flex align-items-center mb-4">
    <div class="me-4">
        <%= image_tag twitter_account.image, class: "rounded-circle"%>
        <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
    </div>

    <%= button_to "Disconnect", twitter_account, method: :delete, data: {confirm: "Are you sure dude?"} %>
</div>

<% end %>